baseURL = "https://spmp.toastbits.dev/"
languageCode = "en-GB"
title = "SpMp"
test = "aaa"

[params]
    latest_version = "0.3.x"
    latest_version_label = "(latest)"
    draft_versions = ["0.4.x"]
    draft_version_label = "(draft)"

    google_fonts = [["Raleway", "500, 700"], ["Fira Code", "500, 700"], ["Rubik", "400"]]
    sans_serif_font = "Rubik"
    secondary_font = "Raleway"
    mono_font = "Fira Code"

[params.footer]
    copyright = "Built with 愛 by [toasterofbread](https://github.com/toasterofbread) using [Hugo](https://github.com/gohugoio/hugo), [Lotus Docs](https://github.com/colinwilson/lotusdocs), and [Catppuccin](https://github.com/catppuccin/catppuccin). The source code of this website is available [here](https://github.com/toasterofbread/spmp-docs)."
    version = true

[params.social]
    github = "toasterofbread/spmp"

[params.docs]
    sidebarIcons = false
    extLinkNewTab = false
    titleIcon = false
    intLinkTooltip = true

[module]
    replacements = "github.com/colinwilson/lotusdocs -> lotusdocs,github.com/gcc42/hugo-redirect -> hugo-redirect"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false
    [[module.imports]]
        path = "github.com/gcc42/hugo-redirect"
        disable = false